INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (1, 'One Piece', 'Adventure');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (2, 'Naruto', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (3, 'Attack on Titan', 'Drama');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (4, 'Fullmetal Alchemist: Brotherhood', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (5, 'Death Note', 'Thriller');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (6, 'Dragon Ball Z', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (7, 'Bleach', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (8, 'Hunter x Hunter', 'Adventure');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (9, 'My Hero Academia', 'Superhero');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (10, 'Demon Slayer', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (11, 'Jujutsu Kaisen', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (12, 'Tokyo Ghoul', 'Horror');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (13, 'Sword Art Online', 'Fantasy');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (14, 'Fairy Tail', 'Adventure');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (15, 'Black Clover', 'Fantasy');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (16, 'Blue Exorcist', 'Supernatural');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (17, 'Neon Genesis Evangelion', 'Mecha');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (18, 'Cowboy Bebop', 'Sci-Fi');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (19, 'Steins;Gate', 'Sci-Fi');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (20, 'Code Geass', 'Mecha');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (21, 'Paranoia Agent', 'Psychological');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (22, 'Psycho-Pass', 'Sci-Fi');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (23, 'Erased', 'Thriller');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (24, 'Akame ga Kill!', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (25, 'Gintama', 'Comedy');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (26, 'Clannad', 'Romance');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (27, 'Your Lie in April', 'Drama');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (28, 'Toradora!', 'Romance');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (29, 'Fruits Basket', 'Drama');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (30, 'KonoSuba', 'Comedy');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (31, 'Re:Zero - Starting Life in Another World', 'Fantasy');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (32, 'No Game No Life', 'Fantasy');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (33, 'The Rising of the Shield Hero', 'Isekai');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (34, 'Overlord', 'Isekai');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (35, 'Log Horizon', 'Fantasy');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (36, 'Made in Abyss', 'Adventure');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (37, 'Dr. Stone', 'Sci-Fi');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (38, 'Great Teacher Onizuka', 'Comedy');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (39, 'Monster', 'Psychological');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (40, 'Trigun', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (41, 'Samurai Champloo', 'Adventure');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (42, 'Rurouni Kenshin', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (43, 'Yu Yu Hakusho', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (44, 'Inuyasha', 'Fantasy');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (45, 'Soul Eater', 'Supernatural');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (46, 'Noragami', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (47, 'Seraph of the End', 'Action');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (48, 'The Seven Deadly Sins', 'Fantasy');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (49, 'Hellsing Ultimate', 'Horror');
INSERT INTO [dbo].[AnimerankingTable] ([ID], [Title], [Genre]) VALUES (50, 'Berserk', 'Dark Fantasy');
